name: pemesanan_makanan_vo1
description: Aplikasi Pemesanan Makanan V.O.1
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP untuk API
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Gambar dari cloud
  cached_network_image: ^3.3.0
  
  # Format currency
  intl: ^0.19.0
  
  # Animasi loading
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/